baseURL = 'https://malinali.app/'
title = 'Malinali'
defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = true

[languages]
[languages.fr]
contentDir = 'content/fr'
languageCode = 'fr-fr'
languageName = 'Français'
weight = 1

[languages.en]
contentDir = 'content/en'
languageCode = 'en-us'
languageName = 'English'
weight = 2

[params]
description = "Malinali - Bridging low-resource natural languages through a simple cross-platform app"
email = "hello@malinali.app"
github = "https://github.com/malinali-app/malinali-app"
